### ISSUE TITLE
Web Server Fails to Start When Using SSL

### ISSUE THREAD

**Issue by thomas-williams** [mesacarlos/WebConsole#105]
Sorry if this is a dupe, or the wrong place to ask this. I have read another issue maybe relating to this, but a lot of what was being tossed around was a bit over my head. I think this might have to do with generating keystore details, and a guide of yours was mentioned, but I could not find a link to it anywhere.

Basically my issue is that my console tells me the web server has failed to start whenever I enable SSL in the config. I won't attach the full log, as it seems like a fairly isolated error. If you need a full log I am happy to provide it. I am running this with Cardboard on Fabric, which you probably (understandably) do not support. Things do however work perfectly even on Cardboard/Fabric without SSL. Any help is greatly appreciated.

```
[02:45:30] [Server thread/INFO]: Enabling WebConsole v2.3
[02:45:30] [Server thread/WARN]: Error occured while starting WebSocket Server.
[02:45:30] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: plugins\WebConsole\keystore.jks (The system cannot find the file specified)
[02:45:30] [Server thread/INFO]: [STDERR]:      at java.base/java.io.FileInputStream.open0(Native Method)
[02:45:30] [Server thread/INFO]: [STDERR]:      at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[02:45:30] [Server thread/INFO]: [STDERR]:      at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[02:45:30] [Server thread/INFO]: [STDERR]:      at es.mesacarlos.webconsole.WebConsole.startWS(WebConsole.java:76)
[02:45:30] [Server thread/INFO]: [STDERR]:      at es.mesacarlos.webconsole.WebConsole.onEnable(WebConsole.java:36)
[02:45:30] [Server thread/INFO]: [STDERR]:      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:257)
[02:45:30] [Server thread/INFO]: [STDERR]:      at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:306)
[02:45:30] [Server thread/INFO]: [STDERR]:      at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[02:45:30] [Server thread/INFO]: [STDERR]:      at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:485)
[02:45:30] [Server thread/INFO]: [STDERR]:      at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:416)
[02:45:30] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$zce000$afterWorldLoad(MinecraftServer.java:1902)
[02:45:30] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:342)
[02:45:30] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3176.method_3823(class_3176.java:182)
[02:45:30] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657)
[02:45:30] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[02:45:30] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by thomas-williams** [comment]
I have found a fabric port of this that works well. Not sure if my issue is specific to using cardboard, or something else, but I'll close this as it is no longer relevant to my particular issue.

**Comment by mesacarlos** [comment]
Hi,
Sorry for my late response,
It seems that the keystore file cannot be found under plugins/WebConsole folder.
The Wiki page you mention on how to enable SSL can be found here: https://github.com/mesacarlos/WebConsole/wiki/SSL-Configuration
