### ISSUE TITLE
TPS not shown and console spams errors.

### ISSUE THREAD

**Issue by argon000s** [mesacarlos/WebConsole#108]
I get this error when using WebConsole version 2.4 and Paper 1.18.1

```
[04:14:53] [WebConsole] User user1 from /[0:0:0:0:0:0:0:1]:59902 as ADMIN successfully logged in.
[04:14:55] java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.MinecraftServer
[04:14:55] at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[04:14:55] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[04:14:55] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[04:14:55] at java.base/java.lang.Class.forName0(Native Method)
[04:14:55] at java.base/java.lang.Class.forName(Class.java:375)
[04:14:55] at WebConsole-2.4.jar//es.mesacarlos.webconsole.websocket.command.TpsCommand.getTps(TpsCommand.java:38)
[04:14:55] at WebConsole-2.4.jar//es.mesacarlos.webconsole.websocket.command.TpsCommand.execute(TpsCommand.java:27)
[04:14:55] at WebConsole-2.4.jar//es.mesacarlos.webconsole.websocket.WSServer.onMessage(WSServer.java:70)
[04:14:55] at WebConsole-2.4.jar//org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:673)
[04:14:55] at WebConsole-2.4.jar//org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:885)
[04:14:55] at WebConsole-2.4.jar//org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:819)
[04:14:55] at WebConsole-2.4.jar//org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
[04:14:55] at WebConsole-2.4.jar//org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
[04:14:55] at WebConsole-2.4.jar//org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1046)
[04:14:55] at WebConsole-2.4.jar//org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1028)
```
and the error repeats every second...

**Comment by mesacarlos** [comment]
Hi, 
Thank you for pointing this out!

I'll investigate and release a hotfix for this.

**Comment by mesacarlos** [comment]
Hello again,
I've just updated v2.4 release to catch unhandled exceptions and stop console spamming in case an error occurs.

You can download the updated jar file [here](https://github.com/mesacarlos/WebConsole/releases/tag/v2.4) or using [Jenkins](https://jenkins.mesacarlos.es/job/WebConsole/78/#:~:text=WebConsole%2D2.4%2Djar,2.42%20MB).

You will see 0 TPS in the web client for now. I think this problem is related to the MC version being to recent, so the method using to retrieve TPS does not work now. I'll investigate this issue.

**Comment by mesacarlos** [comment]
TPS Should be working fine after last build:

https://jenkins.mesacarlos.es/job/WebConsole/109/
