### ISSUE TITLE
Cannot invoke ".getRemoteSocketAddress()" because "conn" is null

### ISSUE THREAD

**Issue by GalacticGreenLemon** [mesacarlos/WebConsole#113]
**The plugin worked fine yesterday but today it gives me this error message and it doesn't open a port.**

[08:16:02 ERROR]: [org.java_websocket.server.WebSocketServer] Shutdown due to fatal error
java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89) ~[?:?]
        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:533) ~[WebConsole-2.4.1.jar:?]
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341) ~[WebConsole-2.4.1.jar:?]
        at es.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:94) ~[WebConsole-2.4.1.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

[08:16:02 WARN]: Exception in thread "WebSocketSelector-44" java.lang.NullPointerException: Cannot invoke "org.java_websocket.WebSocket.getRemoteSocketAddress()" because "conn" is null
[08:16:02 WARN]:        at WebConsole-2.4.1.jar//es.mesacarlos.webconsole.websocket.WSServer.onError(WSServer.java:82)
[08:16:02 WARN]:        at WebConsole-2.4.1.jar//org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:649)
[08:16:02 WARN]:        at WebConsole-2.4.1.jar//org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:542)
[08:16:02 WARN]:        at WebConsole-2.4.1.jar//org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
[08:16:02 WARN]:        at WebConsole-2.4.1.jar//es.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:94)
[08:16:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by GalacticGreenLemon** [comment]
I have two servers and on the other one it seems to work fine so I am very confused as to why this is happening

**Comment by mesacarlos** [comment]
Hello,

Please check that port is not being in use by other instance of your server or any other program

**Comment by GalacticGreenLemon** [comment]
Yes I have checked and it is not. Only port 80 for the website itself, but I don't think that would do anything.
Should I change the port and try again?

**Comment by GalacticGreenLemon** [comment]
I'm kinda new to these kind of things, but I changed it to 1000 and I hope it doesn't matter what the actual port is.
And it seems to do the same thing

**Comment by GalacticGreenLemon** [comment]
could me running java 17 be a problem?

**Comment by GalacticGreenLemon** [comment]
I think I fould the problem
brb after I try

**Comment by GalacticGreenLemon** [comment]
yep, so it was just me being dumb
I am so sorry for taking this time of ur day for nothing
I just put the wrong ip in the config, I put the config from my other server and that one has a different ip

**Comment by GalacticGreenLemon** [comment]
again so sorry for my dumbness
