### ISSUE TITLE
Cannot Connect to the Server

### ISSUE THREAD

**Issue by GenaAaaj** [mesacarlos/WebConsole#133]
![Screenshot_20230604_210321_Chrome](https://github.com/mesacarlos/WebConsole/assets/71671650/a7b96770-49c3-4110-b71e-65acb772c505)
Hi there, i've set up the plugin and the client, but for some reason, when i try to connect vía client i recieve this error:
Cannot connect to the server:
"Make sure that the server is running and that the WebConsole port is open on your firewall and/or router. You can use this tool to check if your port is open."
Im using port 8080 and it seems to be open.
![Screenshot_20230604_103610_Chrome](https://github.com/mesacarlos/WebConsole/assets/71671650/ef419305-c83f-49fa-a72f-7ee9383af924)
config.yml settings:
![16858858778626150314368142779539](https://github.com/mesacarlos/WebConsole/assets/71671650/3c336e6e-1965-4e1b-9e5e-00c696cba5bc)
I my keystore is ok so i think that's not the problem.
If i connect directly (ip:port in browser) i dont even get WebSocket 400 error, i get ERR_INVALID_HTTP_RESPONSE.

Now im getting this in console:
[17:00:03 ERROR]: [org.java_websocket.WebSocketImpl] Exception during channel.close()
java.io.IOException: Connection reset by peer
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54) ~[?:?]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:97) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:53) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532) ~[?:?]
        at org.java_websocket.SSLSocketChannel2.close(SSLSocketChannel2.java:356) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:511) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:545) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.server.WebSocketServer.handleIOException(WebSocketServer.java:633) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:386) ~[WebConsole-2.5.jar:?]
        at es.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:94) ~[WebConsole-2.5.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:00:03 WARN]: [WebConsole] Error occurred on connection /212.102.40.218:25422: java.io.IOException: Connection reset by peer
[17:00:05 ERROR]: [org.java_websocket.WebSocketImpl] Exception during channel.close()
java.io.IOException: Connection reset by peer
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54) ~[?:?]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:97) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:53) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532) ~[?:?]
        at org.java_websocket.SSLSocketChannel2.close(SSLSocketChannel2.java:356) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:511) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:545) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.server.WebSocketServer.handleIOException(WebSocketServer.java:633) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:386) ~[WebConsole-2.5.jar:?]
        at es.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:94) ~[WebConsole-2.5.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:00:05 WARN]: [WebConsole] Error occurred on connection /212.102.40.218:22588: java.io.IOException: Connection reset by peer
[17:00:06 ERROR]: [org.java_websocket.WebSocketImpl] Exception during channel.close()
java.io.IOException: Connection reset by peer
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54) ~[?:?]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:97) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:53) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532) ~[?:?]
        at org.java_websocket.SSLSocketChannel2.close(SSLSocketChannel2.java:356) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:511) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:545) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.server.WebSocketServer.handleIOException(WebSocketServer.java:633) ~[WebConsole-2.5.jar:?]
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:386) ~[WebConsole-2.5.jar:?]
        at es.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:94) ~[WebConsole-2.5.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:00:06 WARN]: [WebConsole] Error occurred on connection /212.102.40.218:44688: java.io.IOException: Connection reset by peer

**Comment by GenaAaaj** [comment]
@mesacarlos pls help

**Comment by mesacarlos** [comment]
Are you using PaperMC or any other? Which MC version are you on?

**Comment by GenaAaaj** [comment]
> Are you using PaperMC or any other? Which MC version are you on?

Hi Carlos, tk for your answer. Im using Paper 1.19.4

**Comment by mesacarlos** [comment]
I cannot replicate this issue. Are you using a selfsigned or a valid certificate?

**Comment by GenaAaaj** [comment]
> I cannot replicate this issue. Are you using a selfsigned or a valid certificate? If switching off SSL, do you still have issues connecting?

I've tried both. Same error, also i re-installed the plugin several times.

**Comment by GenaAaaj** [comment]
I can share my WebConsole folder if you want

**Comment by GenaAaaj** [comment]
WebConsole Folder

<a href="https://www.dropbox.com/s/341gbleyr398vsb/WebConsole.zip?dl=1" download>
  <img src="https://i.imgur.com/VVMF2o9.png" alt="DWNLDBTTN" class="dwn">
</a>

**Comment by GenaAaaj** [comment]
Turning off ssl, the 404 WebSocket Upgrade Failure shows. But when I try to connect from the client, still throwing same error, but now, it takes longer to show it.

![image](https://github.com/mesacarlos/WebConsole/assets/71671650/8ab00ef7-bbd2-45aa-80d7-df787c3e1ef9)

**Comment by GenaAaaj** [comment]
> @mesacarlos Turning off ssl, the 404 WebSocket Upgrade Failure shows. But when I try to connect from the client, still throwing same error, but now, it takes longer to show it.
> 
> ![image](https://user-images.githubusercontent.com/71671650/244892243-8ab00ef7-bbd2-45aa-80d7-df787c3e1ef9.png)
I figured out the issue. I've assigned subdomain "consola." to my nginx server (webconsole client) and that server uses ssl. If i use  @mesacarlos httponly clients it works great. How can i turn ssl off for that subdomain in cloudfare?

**Comment by mesacarlos** [comment]
Glad to hear that you found the issue!
I'm not really into Cloudflare so I cannot help you that much with that.
You can use the httponly clients if that solve your issue!
