### ISSUE TITLE
Paper 1.20.5 & 1.20.6 compatibility

### ISSUE THREAD

**Issue by ThaMunsta** [mesacarlos/WebConsole#150]
The plugin worked fine up to 1.20.4. I was also using java 16 and now am using java 21.

```text
[10:50:52 INFO]: [WebConsole] Enabling WebConsole v2.4
[10:50:52 ERROR]: Error occurred while enabling WebConsole v2.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at WebConsole-2.5.jar/es.mesacarlos.webconsole.websocket.command.WSCommandFactory.getCommandsHashMap(WSCommandFactory.java:14) ~[WebConsole-2.5.jar:?]
        at WebConsole-2.5.jar/es.mesacarlos.webconsole.websocket.WSServer.<init>(WSServer.java:27) ~[WebConsole-2.5.jar:?]
        at WebConsole-2.5.jar/es.mesacarlos.webconsole.WebConsole.startWS(WebConsole.java:65) ~[WebConsole-2.5.jar:?]
        at WebConsole-2.5.jar/es.mesacarlos.webconsole.WebConsole.onEnable(WebConsole.java:36) ~[WebConsole-2.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at WebConsole-2.5.jar/es.mesacarlos.webconsole.websocket.command.TpsCommand.<clinit>(TpsCommand.java:22) ~[WebConsole-2.5.jar:?]
        ... 16 more
[10:50:52 INFO]: [WebConsole] Disabling WebConsole v2.4
[10:50:52 WARN]: java.lang.NullPointerException: Cannot invoke "es.mesacarlos.webconsole.websocket.WSServer.stop()" because "this.server" is null
[10:50:52 WARN]:        at WebConsole-2.5.jar//es.mesacarlos.webconsole.WebConsole.onDisable(WebConsole.java:53)
[10:50:52 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[10:50:52 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237)
[10:50:52 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114)
[10:50:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550)
[10:50:52 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206)
[10:50:52 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[10:50:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[10:50:52 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626)
[10:50:52 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575)
[10:50:52 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[10:50:52 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[10:50:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323)
[10:50:52 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
[10:50:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[10:50:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by mesacarlos** [comment]
Latest release v.6 should solve this.
https://github.com/mesacarlos/WebConsole/releases/tag/v2.6
