### ISSUE TITLE
Server spits out errors when I put in my server IP under 'host'

### ISSUE THREAD

**Issue by noahgonzy** [mesacarlos/WebConsole#16]
When left on localhost, the server has no issues but as soon as I try change it and access it from far away, the server spits out error messages which I don't understand

[09:03:43] [Server thread/INFO]: [WebConsole] Enabling WebConsole v1.5
[09:03:43] [WebSocketSelector-76/WARN]: [WebSocketSelector-76] ERROR org.java_websocket.server.WebSocketServer - Shutdown due to fatal error
[09:03:43] [WebSocketSelector-76/WARN]: java.net.BindException: Cannot assign requested address: bind
[09:03:43] [WebSocketSelector-76/WARN]:         at sun.nio.ch.Net.bind0(Native Method)
[09:03:43] [WebSocketSelector-76/WARN]:         at sun.nio.ch.Net.bind(Unknown Source)
[09:03:43] [WebSocketSelector-76/WARN]:         at sun.nio.ch.Net.bind(Unknown Source)
[09:03:43] [WebSocketSelector-76/WARN]:         at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
[09:03:43] [WebSocketSelector-76/WARN]:         at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
[09:03:43] [WebSocketSelector-76/WARN]:         at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
[09:03:43] [WebSocketSelector-76/WARN]:         at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:505)
[09:03:43] [WebSocketSelector-76/WARN]:         at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315)
[09:03:43] [WebSocketSelector-76/WARN]:         at com.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:122)
[09:03:43] [WebSocketSelector-76/WARN]:         at java.lang.Thread.run(Unknown Source)
[09:03:43] [WebSocketSelector-76/WARN]: Exception in thread "WebSocketSelector-76"
[09:03:43] [Server thread/INFO]: [Essentials] Enabling Essentials v2.17.2.0
[09:03:43] [WebSocketSelector-76/WARN]: java.lang.NullPointerException
[09:03:43] [WebSocketSelector-76/WARN]:         at com.mesacarlos.webconsole.websocket.WSServer.onError(WSServer.java:76)
[09:03:43] [WebSocketSelector-76/WARN]:         at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:618)
[09:03:43] [WebSocketSelector-76/WARN]:         at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:514)
[09:03:43] [WebSocketSelector-76/WARN]:         at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315)
[09:03:43] [WebSocketSelector-76/WARN]:         at com.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:122)
[09:03:43] [WebSocketSelector-76/WARN]:         at java.lang.Thread.run(Unknown Source)

I obviously then can't connect to the plugin via the web interface

Anythinkg I'm doing wrong? ports are forwarded and all

**Comment by mesacarlos** [comment]
Hello,
Do you put a numeric address or a domain? Are you on Linux or Windows?
I assume that port is not in use by any other program as everything works using localhost...
Is the IP address correct?

**Comment by noahgonzy** [comment]
I'm using a domain, I'm on windows, the IP is definitely correct, If localhost should work, I'll give it another try but when I try add the server using the client, It doesn't detect it, using localhost or not

**Comment by mesacarlos** [comment]
Hello,
Try using the numeric IP, that should do the trick.
Also, on Windows it should also allow remote connections leaving localhost.

Please check and reply if your problem is solved.

**Comment by noahgonzy** [comment]
I attempted using the numeric ID, I still get an error message, along with new ones as the server runs. should using localhost even work if I attempt to connect once leaving localhost using my computer's IP?

**Comment by mesacarlos** [comment]
Hello again,
I just did some testing on Windows 10:
Please try using your LAN IP address, it should be something like 192.168.xxx.xxx or 10.xxx.xxx.xxx.
That should solve all the problems ;)

Please reply if that solves the problem or you still have issues.

**Comment by noahgonzy** [comment]
Working perfectly now, thanks so much, gonna make this quarentine period where I can't get to my PC much easier :P

Love the plugin man, exactly what I needed

Just maybe mention on the bukkit page that you need to use your local IP as the 'host' section of the config 

Thanks again <3
