### ISSUE TITLE
java.net.bind.exception when restarting the server

### ISSUE THREAD

**Issue by opiumcloud** [mesacarlos/WebConsole#17]
Hi! We're trying to use your plugin on a Debian server running the latest version of Paper. Everything seems to work okay, excepting that when the Paper server is restarted WebConsole doesn't start, detecting that the direction is yet in use. It seems that the only solution is to change WebConsole's port each time we restart or restarting the whole server, which doesn't sound very practical. 

By the way, we love your plugin and would like to be able to use it. Is there anything that we can do in order to solve that issue? Thanks in advance

```
[14:55:18] [Server thread/INFO]: [WebConsole] Enabling WebConsole v1.5
[14:55:18] [WebSocketSelector-72/ERROR]: [org.java_websocket.server.WebSocketServer] Shutdown due to fatal error
java.net.BindException: La dirección ya está en uso
        at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_252-ea]
        at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_252-ea]
        at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_252-ea]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220) ~[?:1.8.0_252-ea]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85) ~[?:1.8.0_252-ea]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:78) ~[?:1.8.0_252-ea]
        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:505) ~[?:?]
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315) ~[?:?]
        at com.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:122) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252-ea]
[14:55:18] [WebSocketSelector-72/WARN]: Exception in thread "WebSocketSelector-72" java.lang.NullPointerException
[14:55:18] [WebSocketSelector-72/WARN]:         at com.mesacarlos.webconsole.websocket.WSServer.onError(WSServer.java:76)
[14:55:18] [WebSocketSelector-72/WARN]:         at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:618)
[14:55:18] [WebSocketSelector-72/WARN]:         at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:514)
[14:55:18] [WebSocketSelector-72/WARN]:         at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315)
[14:55:18] [WebSocketSelector-72/WARN]:         at com.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:122)
[14:55:18] [WebSocketSelector-72/WARN]:         at java.lang.Thread.run(Thread.java:748)

```

**Comment by mesacarlos** [comment]
Hello,
I was not able to reproduce this issue on last Paper version (1.15.2, build 155).
Do it happens on every realod, or only in some reloads?

Can you please provide me your `port` and `host` values of your config.yml?

**Comment by opiumcloud** [comment]
Hi!
It happens to us in every reload. The port is `8282` and the host `192.168.1.111`

**Comment by mesacarlos** [comment]
Hi,
Your config.yml seems to be okay.
After several days, I haven't been able to reproduce the problem. This makes me think that is related to some of your other installed plugins. If you can, please provide me the list of plugins you are using.

**Comment by opiumcloud** [comment]
Nowadays we are not using any plugins other than WebConsole. We'll try changing the host ip address and making some changes.

**Comment by mesacarlos** [comment]
Considering this issue solved.
