### ISSUE TITLE
Error address already in use

### ISSUE THREAD

**Issue by martino-dot** [mesacarlos/WebConsole#42]
When I start the server it gives me an error saying ```[WebSocketSelector-35] ERROR org.java_websocket.server.WebSocketServer - Shutdown due to fatal error```, right after enabling webconsole. It has a unique port and ip. What could be the problem?

**Comment by mesacarlos** [comment]
Hi,
Can you please copypaste the full exception?

**Comment by martino-dot** [comment]
Sure, ```[01:07:22] [Server thread/INFO]: [WebConsole] Enabling WebConsole v2.0
[01:07:22] [WebSocketSelector-35/WARN]: [WebSocketSelector-35] ERROR org.java_websocket.server.WebSocketServer - Shutdown due to fatal error
[01:07:22] [WebSocketSelector-35/WARN]: java.net.BindException: Address already in use
[01:07:22] [WebSocketSelector-35/WARN]:         at sun.nio.ch.Net.bind0(Native Method)
[01:07:22] [WebSocketSelector-35/WARN]:         at sun.nio.ch.Net.bind(Net.java:433)
[01:07:22] [WebSocketSelector-35/WARN]:         at sun.nio.ch.Net.bind(Net.java:425)
[01:07:22] [WebSocketSelector-35/WARN]:         at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
[01:07:22] [WebSocketSelector-35/WARN]:         at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
[01:07:22] [WebSocketSelector-35/WARN]:         at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:533)
[01:07:22] [WebSocketSelector-35/WARN]:         at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
[01:07:22] [WebSocketSelector-35/WARN]:         at es.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:129)
[01:07:22] [WebSocketSelector-35/WARN]:         at java.lang.Thread.run(Thread.java:748)
[01:07:22] [WebSocketSelector-35/WARN]: Exception in thread "WebSocketSelector-35" 
[01:07:22] [WebSocketSelector-35/WARN]: java.lang.NullPointerException
[01:07:22] [WebSocketSelector-35/WARN]:         at es.mesacarlos.webconsole.websocket.WSServer.onError(WSServer.java:78)
[01:07:22] [WebSocketSelector-35/WARN]:         at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:649)
[01:07:22] [WebSocketSelector-35/WARN]:         at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:542)
[01:07:22] [WebSocketSelector-35/WARN]:         at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:341)
[01:07:22] [WebSocketSelector-35/WARN]:         at es.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:129)
[01:07:22] [WebSocketSelector-35/WARN]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by mesacarlos** [comment]
What are your IP and port values of your config.yml?

**Comment by martino-dot** [comment]
The ip is 10.0.2.1 and my port is 8080.

**Comment by mesacarlos** [comment]
Please double check that port 8080 is not already in use (maybe your mc server is already opened with webconsole running on that port)
Also try replacing your ip with 0.0.0.0

**Comment by martino-dot** [comment]
Thanks. The port fixed it.
