### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by qwer2415wy** [mesacarlos/WebConsole#52]
[06:00:56 WARN]: java.io.FileNotFoundException: plugins/WebConsole/keystore.jks (No such file or director    y)
[06:00:56 WARN]:        at java.io.FileInputStream.open0(Native Method)
[06:00:56 WARN]:        at java.io.FileInputStream.open(FileInputStream.java:195)
[06:00:56 WARN]:        at java.io.FileInputStream.<init>(FileInputStream.java:138)
[06:00:56 WARN]:        at es.mesacarlos.webconsole.WebConsole.startWS(WebConsole.java:76)
[06:00:56 WARN]:        at es.mesacarlos.webconsole.WebConsole.onEnable(WebConsole.java:36)
[06:00:56 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[06:00:56 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337    )
[06:00:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:40    3)
[06:00:56 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[06:00:56 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330    )
[06:00:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[06:00:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[06:00:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[06:00:56 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[06:00:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[06:00:56 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by mesacarlos** [comment]
#46
