### ISSUE TITLE
Cannot load plugin in Papermc: Invalid plugin.yml

### ISSUE THREAD

**Issue by AlphaJack** [mesacarlos/WebConsole#82]
This is the only plugin I am unable to load in Papermc. From server logs:

```
[...]
[12:34:03] [Server thread/INFO]: Paper: Using OpenSSL (Linux aarch64) cipher from Velocity.
[12:34:03] [Server thread/ERROR]: Could not load 'plugins/WebConsole-2.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[patched_1.17.1.jar:git-Paper-243]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.17.1.jar:git-Paper-243]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:410) ~[patched_1.17.1.jar:git-Paper-243]
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:276) ~[patched_1.17.1.jar:git-Paper-243]
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-243]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-243]
    at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
    at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1608) ~[?:?]
    at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1460) ~[?:?]
    at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1469) ~[?:?]
    at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1281) ~[?:?]
    at java.util.zip.ZipFile$Source.get(ZipFile.java:1243) ~[?:?]
    at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:707) ~[?:?]
    at java.util.zip.ZipFile.<init>(ZipFile.java:241) ~[?:?]
    at java.util.zip.ZipFile.<init>(ZipFile.java:171) ~[?:?]
    at java.util.jar.JarFile.<init>(JarFile.java:348) ~[?:?]
    at java.util.jar.JarFile.<init>(JarFile.java:319) ~[?:?]
    at java.util.jar.JarFile.<init>(JarFile.java:285) ~[?:?]
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[patched_1.17.1.jar:git-Paper-243]
    ... 6 more
[12:34:03] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.6.0-beta2-b2453
[...]
```

Any idea why?

**Comment by mesacarlos** [comment]
Hi,
Try redownloading the .jar file and/or reuploading it to your server, maybe there was a problem with the transfer and the zip file got corrupted.
